### ISSUE TITLE
[Enfold] Problems with translated images after upgrade to 4.0.4

### ISSUE THREAD

**Issue by InoPlugs** [OnTheGoSystems/wpml-config#37] opened 2018-07-16 14:38 UTC
Hi @amElnagdy 

We experience a few users having troubles with translated images after upgrading WPML - images are not shown in translated page.

## How to reproduce

Create an Adanced Layout builder page with e.g. image, masonry gallery, logoslider (these element store the id of uploaded images in the shortcode parameter)

After upgrade of WPML the images are no longer visible in the translated page.

## Solution that works on my dev servers

I fixed the query for image information by using get_posts (instead of get_post). This returns the translated images after having run the "translate image" from settings page. Before running this I recieved only an empty array (and not the original image as a fallback - adding this would at least fix the problem of getting no images at all ??).

Other elements use WP_Query but this results in a get_posts so this also work.

## User sites (using translation management)

I provided users with the updated files, told them to run the translation routine, but:

- still no images are visible

I checked the translated page content - the id's of the original image are in the shortcode (which is OK because we translate the images on the fly when the shortcode is executed).

One user already contacted you and I will tell the other one to do the same.

**Comment by amElnagdy** [comment] 2018-07-16 16:35
@InoPlugs 
I have tested with the upcoming WPML 4.0.5-dev and the issue seems to be resolved. You can check the page here http://enfold.compatibility.wpml.org/issue-37/ and the translation is here http://enfold.compatibility.wpml.org/fr/fr-issue-37/

As I have you here, could you please provide me with the upcoming release dev version to upload it to our testing servers? (and will you keep using get_posts?)

**Comment by InoPlugs** [comment] 2018-07-17 11:37
@amElnagdy 

At a quick glance we still use get_post but mainly with page or post or menu - and there are still some images left. Trying to fix the problem I only concentrated on shortcodes.

For pages get_post works because I checked it with a custom 404 and maintenance page.

If it makes troubles for you to translate images with get_post I think we can switch for the remaining queries to get_posts and stick to it in future.

Our current released version is 4.4.1. We have a lot of open pull requests and I do not know, what Kriesi will merge for the next release.

What I can give you is my branch with the adjustments for WPML up to now - would that help you?

**Comment by amElnagdy** [comment] 2018-07-17 11:43
@InoPlugs yes, it would be great.

**Comment by InoPlugs** [comment] 2018-07-17 11:52
@amElnagdy 

This issue seems to be public - how can I send you the zip - or shall I upload it here and you delete it when downloaded?

**Comment by amElnagdy** [comment] 2018-07-17 12:35
You can send it here ahmed.m@onthegosystems.com @InoPlugs

**Comment by InoPlugs** [comment] 2018-07-17 13:13
@amElnagdy 

Sent you the file.

Let us know if we need to switch all image queries to get_posts and if you need something else to fix.

**Comment by amElnagdy** [comment] 2018-07-17 13:59
Thanks a lot, @InoPlugs.
I have received the files. I'll test the issue mentioned here again and check if anything else needs fixing and contact you about it.

**Comment by amElnagdy** [comment] 2018-07-27 12:48
@InoPlugs I think the issue is really resolved with your updated files. A lot of tests have been done in that ticket and it seems everything is fine regarding this issue.

**Closed by amElnagdy** 2018-07-27 12:48 UTC

**Comment by InoPlugs** [comment] 2018-07-30 13:50
@amElnagdy 

Thanks for the info. Which version of WPML will include your fixes?

**Comment by amElnagdy** [comment] 2018-07-30 13:51
@InoPlugs WPML 4.0.5 and also the online config file we have here https://s3.amazonaws.com/wpmlorg/wpml-config/enfold/wpml-config.xml includes some settings for the missing custom fields.

**Comment by amElnagdy** [comment] 2018-07-31 12:12
@InoPlugs sure. A developer account will be created and sent to your email.

**Comment by InoPlugs** [comment] 2018-08-01 12:51
@amElnagdy 

Thanks.

I sent you an updated version of Enfold containing a small bugfix for Logoelement.
